Modify mail.send() to catch send being called outside of ir_mail_server.send_mail()
WilldooIT/odoo pull request #129
Opened 2022-10-26 06:34 UTC by james-willdooit

Eg. Send mail wizard, send message from chatter

2022-10-26 06:36 UTC, james-willdooit commented on addons/mail/models/mail_mail.py
> +            if self.env['ir.config_parameter'].sudo().get_param('mail.email_db_whitelist_fail_silent'):
The logic here is to ensure compatibility for some views that rely on this method returning True, eg: Send Message from document chatter

2022-10-28 03:51 UTC, richard-willdooit requested changes

2022-10-28 03:51 UTC, richard-willdooit commented on addons/mail/models/mail_mail.py
> +from odoo.exceptions import UserError
Don't need UserError

2022-10-28 04:18 UTC, richard-willdooit approved these changes

2022-10-28 04:33 UTC, merged